services:
  - type: web
    name: mental-health-companion
    env: node
    plan: free
    buildCommand: npm run install-all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GEMINI_API_KEY
        sync: false
        description: "Your Google Gemini API key for AI chat functionality"
    healthCheckPath: /api/chat
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*"
        - "!node_modules/**"
        - "!.git/**"
